### ISSUE TITLE
update the configuration machinery to take class-level info

### ISSUE THREAD

**Issue by leondz** [leondz/garak#595]
Config expressed in a reasonable YAML should follow through to plugin configuration

e.g. a site config like
```
(garak) 11:03:34 x1:~/dev_ext/garak [feature/hf_config] $ cat garak/garak.site.yaml 
plugins:
  generators:
    huggingface:
      Pipeline:
        dtype: bfloat16
```

should lead instances of `garak.generators.huggingface.Pipeline` to have a `dtype` attribute set to `"bfloat16"`

Currently, a config like this yields:

```
>>> garak._config.load_config()
>>> garak._config.plugins.generators
{'huggingface': {'dtype': 'bfloat16'}}
```

The plugin loading + configuring code doesn't pass this on to the generator (partly because generators don't load using that code, until the broader issue around #589 is resolved)

We should prefer sensible YAML like above. It's possible to make the YAML look different and then have things fit but this is unintuitive for innocent folks just trying to write a sane config file. So, to get these to propagate, we should do something like:

* get into those dicts in `configure_plugin`
* store configs using nested dataclasses or something, to avoid the unintuitive dataclass-to-dict switch

I'm slightly unsatisfied with how defaults, None, and absent values are treated in the dataclass approach - open to doing something better
