### ISSUE TITLE
Reorganise `_config` - move run-specific items out of `plugins`

### ISSUE THREAD

**Issue by leondz** [leondz/garak#931]
## Summary

Move the following from `_config.plugins` to `_config.run`:

* model_type
* model_name
* extended_detectors
* probe_spec
* detector_spec
* buff_spec

Test at least that:

* they're present in `_config.run`
* they're correctly populated in `_config.run`
* they're absent in `_config.plugins`
* each one is picked up correctly in at least one place

### Basic example

the following config becomes valid:

```
---
run:
  model_name: openai
  probe_spec: encoding
plugins:
  generators:
    openai:
      OpenAIGenerator:
        name: gpt-4
```

### Motivation

Items that shape the current run, and affect what is tested for, must be placed in `_config.run`. The contents of `_config.plugins` specify how plugins run, if they run. `_config.run` is about orchestration. `_config.plugins` is about helping individual plugins and plugin families execute.
